apiVersion: v2
name: platform-observability-stack
description: End-to-end observability (LGTM + Alloy + MinIO)
version: 1.0.0
dependencies:

  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled

  - name: tempo
    version: 1.24.4
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled

  # - name: loki
  #   version: 5.43.0
  #   repository: https://grafana.github.io/helm-charts
  #   condition: loki.enabled

  # - name: prometheus
  #   version: 25.21.0
  #   repository: https://prometheus-community.github.io/helm-charts
  #   condition: prometheus.enabled

  # - name: alloy
  #   version: 0.1.1
  #   repository: https://grafana.github.io/helm-charts
  #   condition: alloy.enabled
  # - name: grafana
  #   version: 7.3.7
  #   repository: https://grafana.github.io/helm-charts
  #   condition: grafana.enabled