apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: model
  namespace: default
  annotations:
    serving.kserve.io/ingress-class: "istio"
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      runtime: kserve-mlserver 
      storageUri: "iris-models-114223852322-us-east-1-an/mlartifacts/models/m-1dc13068ce3a4a63abaf51848a461df9/artifacts/"
      resources:
        limits:
          cpu: "500m"
          memory: 1Gi
        requests:
          cpu: "100m"
          memory: 500Mi
