apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: model
  namespace: default
  annotations:
    serving.kserve.io/ingress-class: "istio"
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      runtime: kserve-mlserver 
      storageUri: "s3://iris-models-114223852322-us-east-1-an/mlartifacts/models/m-06ccb2dbb0034be8b3f86500e13e61e7/artifacts/"
      resources:
        limits:
          cpu: "500m"
          memory: 1Gi
        requests:
          cpu: "100m"
          memory: 500Mi
