apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: creative-local-cert
  namespace: istio-system
spec:
  isCA: false
  secretName: creative-tls-secret 
  issuerRef:
    name: local-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "creative.opik.net"
    - "*.creative.opik.net"