# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: github-runner-token
#   namespace: actions-runner-system
# spec:
#   encryptedData:
#     github_token: AgCCNcEusDvsHpBcZRDoDFPMGN51AZTVV5pRkwZRt4S9ApcnB7LyAuzcrjYXHIg9epwtGS3tArPqozFlbY0BEOHu/1jESUfOGR7f4jwJQHO65AS0DYt2HMY9xABMDb4e1HbcKFZvqsgeLvsxG80jwO01DAKDDrCbjBE16pAO/FmQfn07zJOuV7H3spc7mVH3c9Uy9iNRKlAWb2rPXKoFNrn2VoDaowf6BGpNGaJ22ZUoF6lWq5WYEwEaxXhl3Jx15NbZAxAhzk4yhUhkxrU9kFyIj5vP2OoGXiG4fDXmV8GwjA3OStiP9rB/tNXjDC2lENUMbn4xgBWccbnviPQzyZBU6GKiiRsPnh88x8DsVbRaRQY4d1IZJViWEhgUr2qa9Vmxo3q8NNQtLgR5ysl8k3VcZGYfEDgwZyrFJxLWdZzwRFb8Com4cNReAzlPXZ+M0pMXyG9xT7kZjWqEn57QfcdHJoRdOF0sd2nwvNedjm9hhS2qW8wldQO4b91puARyyJq6oQDd5hsubu7qOhIBnUa1IyXR5IXDkCFGfh85Vv766t7T7pQ3uZ4RnpVoIsfRQSGFlOz/OiKiP7MuMi3mlsi/TcmMenB3pbqpQ27hc/c4WiyOoENML6QgCyYdB7zwBTrFjkHMZy/UB3i2Q+FJwztNd1tNcSptaDTQyzzcyfquMFBDGDudSREA1xRH8aWI8Y6h3/vBArxgbCcrllhO3WWu4GuPUzbm/qK/SPXda9B0VfMXZtwYImoC
#   template:
#     metadata:
#       name: github-runner-token
#       namespace: actions-runner-system
#     type: Opaque