apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/bitnami-labs/sealed-secrets.git'
    targetRevision: main
    path: helm/sealed-secrets
    helm:
      values: |
        fullnameOverride: "sealed-secrets-controller"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true