# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: platform-api-virtualservice
#   namespace: platform-apps 
# spec:
#   hosts:
#   - "creative.opik.net"
#   gateways:
#   - istio-system/kubevision-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /
#     route:
#     - destination:
#         host: platform-api-svc.platform-apps.svc.cluster.local
#         port:
#           number: 80 