# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: platform-api-premission
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "19" 
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: 'https://github.com/AdhamAyad/KubeVision-Serverless-Platform.git'
#     targetRevision: main
#     path: Kubernetes/api-permission
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: platform-apps
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true