apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sklearn-iris-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13" 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/AdhamAyad/KubeVision-Serverless-Platform.git'
    targetRevision: main
    path: Kubernetes/workloads/sklearn-iris
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true