name: "Infrastructure & Config Provisioning"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Terraform/**'
      - 'Ansible/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy: 
    name: "Deploy Infrastructure and Apps"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            terraform:
              - 'Terraform/**'
            ansible:
              - 'Ansible/**'

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::439328746854:role/terraform
          aws-region: us-east-1 
      
      - name: Setup Terraform
        if: steps.filter.outputs.terraform == 'true' || github.event_name == 'workflow_dispatch'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.2" 

      - name: Terraform Init
        if: steps.filter.outputs.terraform == 'true' || github.event_name == 'workflow_dispatch'
        working-directory: ./Terraform
        run: terraform init

      - name: Terraform Plan
        if: steps.filter.outputs.terraform == 'true' || github.event_name == 'workflow_dispatch'
        working-directory: ./Terraform
        run: terraform plan -parallelism=10 -no-color
        env:
          TF_LOG: INFO

      - name: Terraform Apply
        if: steps.filter.outputs.terraform == 'true' || github.event_name == 'workflow_dispatch'
        working-directory: ./Terraform
        run: terraform apply -auto-approve -input=false

      - name: Update KubeConfig
        if: steps.filter.outputs.ansible == 'true' || steps.filter.outputs.terraform == 'true' || github.event_name == 'workflow_dispatch'
        run: aws eks update-kubeconfig --region us-east-1 --name KubeVision-prod

      - name: Install Ansible and K8s dependencies
        if: steps.filter.outputs.ansible == 'true' || steps.filter.outputs.terraform == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          pip install ansible kubernetes pyyaml
          ansible-galaxy collection install kubernetes.core

      - name: Run Ansible Playbook to Install ArgoCD
        if: steps.filter.outputs.ansible == 'true' || steps.filter.outputs.terraform == 'true' || github.event_name == 'workflow_dispatch'
        working-directory: ./Ansible 
        run: ansible-playbook setup-cluster.yaml

      - name: Deploy Master App (App-of-Apps)
        working-directory: ./Kubernetes/bootstrap
        run: kubectl apply -f app-of-apps.yaml